### ISSUE TITLE
Conclusions?

### ISSUE THREAD

**Issue by Jipok** [yak-labs/chirp-lang#1]
I am interested in developing my own language based on tcl. I It seems like you have done the most work among all go implementations. Can you share your experience? Have you made any conclusions? Are there any unsolvable difficulties that made you abandon the project? Is there anything you can recommend learning? What would you do differently if you had to write from scratch?

**Comment by Jipok** [comment]
@strickyak

**Comment by strickyak** [comment]
1.  Go was an excellent choice for my TCL interpreter.  I continue to use it for projects like this.  
2.  We made different choices in how we implemented "swizzling" in our TCL, than in the standard TCL interpreter.  It has some implications in how fast code runs.  Ours is a little less dynamic than the C implementation, but a little simpler to build.  This hasn't been a problem, but we are aware of it.
3. Since Go is garbage collected but C is not, we can generalize TCL hashes a little.  We can pass hashes as a value, and it will be garbage collected when needed.  Normal TCL cannot pass a hash as a value, but you can refer to one in an outer scope with upvar.  
4. We did a few nonstandard things that I sort of regret.   Like distinguishing global variables by the "Go" rule, that they start with an uppercase letter.   It's convenient, but nonstandard. 
5. So try your project and let me know what you find!   thanks, strick
